import type { LucideIcon } from 'lucide-react';
import {
  FileText,
  FileArchive,
  Minimize,
  ScanText,
  Eraser,
  QrCode,
  CopyCheck,
  SpellCheck,
  WrapText,
  UserSquare,
  Bot,
  Calculator,
  Recycle,
  Landmark,
  Braces,
  Code,
  MonitorSmartphone,
  Tags,
  Mail,
  FileUp,
  FileDown,
  Image,
  Type,
  Terminal,
  Settings,
} from 'lucide-react';

export type ToolCategory = 'PDF' | 'Image' | 'Text' | 'Dev' | 'Utilities';

export type Tool = {
  name: string;
  description: string;
  href: string;
  icon: LucideIcon;
  category: ToolCategory;
  implemented: boolean;
};

export const tools: Tool[] = [
  {
    name: 'PDF to Word',
    description: 'Convert PDFs to Word',
    href: '/tools/pdf-to-word',
    icon: FileUp,
    category: 'PDF',
    implemented: false,
  },
  {
    name: 'Word to PDF',
    description: 'Transform Word to PDF',
    href: '/tools/word-to-pdf',
    icon: FileDown,
    category: 'PDF',
    implemented: false,
  },
  {
    name: 'PDF Compressor',
    description: 'Reduce PDF file size',
    href: '/tools/pdf-compressor',
    icon: FileArchive,
    category: 'PDF',
    implemented: false,
  },
  {
    name: 'Image Compressor',
    description: 'Compress image size',
    href: '/tools/image-compressor',
    icon: Minimize,
    category: 'Image',
    implemented: false,
  },
  {
    name: 'Image to Text (OCR)',
    description: 'Extract text from images',
    href: '/tools/image-to-text',
    icon: ScanText,
    category: 'Image',
    implemented: false,
  },
  {
    name: 'Background Remover',
    description: 'Remove image background',
    href: '/tools/background-remover',
    icon: Eraser,
    category: 'Image',
    implemented: true,
  },
  {
    name: 'QR Code Generator',
    description: 'Generate QR codes',
    href: '/tools/qr-code-generator',
    icon: QrCode,
    category: 'Utilities',
    implemented: true,
  },
  {
    name: 'Plagiarism Checker',
    description: 'Detect copied content',
    href: '/tools/plagiarism-checker',
    icon: CopyCheck,
    category: 'Text',
    implemented: true,
  },
  {
    name: 'Grammar Checker',
    description: 'Check grammar and spelling',
    href: '/tools/grammar-checker',
    icon: SpellCheck,
    category: 'Text',
    implemented: true,
  },
  {
    name: 'Text Summarizer',
    description: 'Summarize long text',
    href: '/tools/text-summarizer',
    icon: WrapText,
    category: 'Text',
    implemented: true,
  },
  {
    name: 'Resume Builder',
    description: 'Create professional resumes',
    href: '/tools/resume-builder',
    icon: UserSquare,
    category: 'Utilities',
    implemented: false,
  },
  {
    name: 'AI Essay Writer',
    description: 'Generate essays with AI',
    href: '/tools/ai-essay-writer',
    icon: Bot,
    category: 'Text',
    implemented: true,
  },
  {
    name: 'Age Calculator',
    description: 'Calculate your age',
    href: '/tools/age-calculator',
    icon: Calculator,
    category: 'Utilities',
    implemented: true,
  },
  {
    name: 'Unit Converter',
    description: 'Convert measurement units',
    href: '/tools/unit-converter',
    icon: Recycle,
    category: 'Utilities',
    implemented: false,
  },
  {
    name: 'Currency Converter',
    description: 'Convert currencies',
    href: '/tools/currency-converter',
    icon: Landmark,
    category: 'Utilities',
    implemented: false,
  },
  {
    name: 'JSON Formatter',
    description: 'Format and validate JSON',
    href: '/tools/json-formatter',
    icon: Braces,
    category: 'Dev',
    implemented: true,
  },
  {
    name: 'Code Minifier',
    description: 'Minify CSS, JS, HTML',
    href: '/tools/code-minifier',
    icon: Code,
    category: 'Dev',
    implemented: false,
  },
  {
    name: 'Website Screenshot',
    description: 'Take a full-page screenshot',
    href: '/tools/website-screenshot',
    icon: MonitorSmartphone,
    category: 'Utilities',
    implemented: false,
  },
  {
    name: 'Meta Tag Generator',
    description: 'Generate meta tags for SEO',
    href: '/tools/meta-tag-generator',
    icon: Tags,
    category: 'Dev',
    implemented: false,
  },
  {
    name: 'Temp Email Generator',
    description: 'Create a temporary email',
    href: '/tools/temp-email-generator',
    icon: Mail,
    category: 'Utilities',
    implemented: false,
  },
];
