import type { LucideIcon } from 'lucide-react';
import {
  FileText,
  FileDown,
  FileArchive,
  Minimize,
  ScanText,
  Eraser,
  QrCode,
  CopyCheck,
  SpellCheck,
  WrapText,
  UserSquare,
  Bot,
  Calculator,
  Recycle,
  Landmark,
  Braces,
  Code,
  MonitorSmartphone,
  Tags,
  ImageIcon,
  Type,
  Scissors,
  BookOpen,
  FileUser,
  PenTool,
  Calendar,
  Ruler,
  DollarSign,
  Tag,
  Thermometer,
  BookText,
  Newspaper,
  Repeat,
  Lock,
  Receipt,
} from 'lucide-react';

export type ToolCategory = 'PDF' | 'Image' | 'Text' | 'Dev' | 'Utilities' | 'Security' | 'Business' | 'Finance';

export type Tool = {
  name: string;
  description: string;
  href: string;
  icon: LucideIcon;
  category: ToolCategory;
  implemented: boolean;
};

export const tools: Tool[] = [
  {
    name: 'Word to PDF',
    description: 'Convert Word to PDF',
    href: '/tools/word-to-pdf',
    icon: FileDown,
    category: 'PDF',
    implemented: true,
  },
  {
    name: 'PDF Compressor',
    description: 'Reduce PDF file size',
    href: '/tools/pdf-compressor',
    icon: FileArchive,
    category: 'PDF',
    implemented: true,
  },
  {
    name: 'Image Compressor',
    description: 'Compress images quickly',
    href: '/tools/image-compressor',
    icon: ImageIcon,
    category: 'Image',
    implemented: true,
  },
  {
    name: 'Image to Text (OCR)',
    description: 'Extract text from images',
    href: '/tools/image-to-text',
    icon: Type,
    category: 'Image',
    implemented: true,
  },
  {
    name: 'Background Remover',
    description: 'Remove background from images',
    href: '/tools/background-remover',
    icon: Scissors,
    category: 'Image',
    implemented: true,
  },
  {
    name: 'QR Code Generator',
    description: 'Create QR codes',
    href: '/tools/qr-code-generator',
    icon: QrCode,
    category: 'Utilities',
    implemented: true,
  },
  {
    name: 'Plagiarism Checker',
    description: 'Check for copied content',
    href: '/tools/plagiarism-checker',
    icon: CopyCheck,
    category: 'Text',
    implemented: true,
  },
  {
    name: 'Grammar Checker',
    description: 'Grammar & spell check',
    href: '/tools/grammar-checker',
    icon: SpellCheck,
    category: 'Text',
    implemented: true,
  },
  {
    name: 'Text Summarizer',
    description: 'Summarize long text',
    href: '/tools/text-summarizer',
    icon: BookOpen,
    category: 'Text',
    implemented: true,
  },
  {
    name: 'Resume Builder',
    description: 'Create professional resumes',
    href: '/tools/resume-builder',
    icon: FileUser,
    category: 'Utilities',
    implemented: true,
  },
  {
    name: 'AI Essay Writer',
    description: 'Generate essays with AI',
    href: '/tools/ai-essay-writer',
    icon: PenTool,
    category: 'Text',
    implemented: true,
  },
  {
    name: 'Invoice Generator',
    description: 'Create professional invoices and download as PDF instantly for free',
    href: '/tools/invoice-generator',
    icon: Receipt,
    category: 'Business',
    implemented: true,
  },
  {
    name: 'Loan Calculator',
    description: 'Calculate monthly EMI and total interest for any loan instantly',
    href: '/tools/loan-calculator',
    icon: Calculator,
    category: 'Finance',
    implemented: true,
  },
  {
    name: 'Age Calculator',
    description: 'Calculate age from DOB',
    href: '/tools/age-calculator',
    icon: Calendar,
    category: 'Utilities',
    implemented: true,
  },
  {
    name: 'Unit Converter',
    description: 'Convert units quickly',
    href: '/tools/unit-converter',
    icon: Ruler,
    category: 'Utilities',
    implemented: true,
  },
  {
    name: 'Currency Converter',
    description: 'Live currency conversion',
    href: '/tools/currency-converter',
    icon: DollarSign,
    category: 'Utilities',
    implemented: true,
  },
  {
    name: 'JSON Formatter',
    description: 'Pretty-print JSON',
    href: '/tools/json-formatter',
    icon: Braces,
    category: 'Dev',
    implemented: true,
  },
  {
    name: 'Code Minifier',
    description: 'Minify JS/CSS/HTML',
    href: '/tools/code-minifier',
    icon: Code,
    category: 'Dev',
    implemented: true,
  },
  {
    name: 'Meta Tag Generator',
    description: 'Generate SEO meta tags',
    href: '/tools/meta-tag-generator',
    icon: Tag,
    category: 'Dev',
    implemented: true,
  },
  {
    name: 'Weather Checker',
    description: 'Get live weather updates',
    href: '/tools/weather-checker',
    icon: Thermometer,
    category: 'Utilities',
    implemented: true,
  },
  {
    name: 'Dictionary',
    description: 'Find word definitions',
    href: '/tools/dictionary',
    icon: BookText,
    category: 'Text',
    implemented: true,
  },
  {
    name: 'Text Repeater',
    description: 'Repeat any text multiple times with custom separators instantly',
    href: '/tools/text-repeater',
    icon: Repeat,
    category: 'Text',
    implemented: true,
  },
  {
    name: 'Word Counter',
    description: 'Count words, characters, sentences and reading time instantly',
    href: '/tools/word-counter',
    icon: FileText,
    category: 'Text',
    implemented: true,
  },
  {
    name: 'Password Generator',
    description: 'Generate strong secure passwords with custom length and characters instantly',
    href: '/tools/password-generator',
    icon: Lock,
    category: 'Security',
    implemented: true,
  },
];
